# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        name:
          [
            "ubuntu-py36",
            "ubuntu-py37",
            "ubuntu-py38",
            "ubuntu-py39",
            "windows-py38",
            "ubuntu-py38-conan1.17",
          ]
        include:
          - name: "ubuntu-py36"
            python: "3.6"
            conan: "latest"
            os: ubuntu-latest
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
            conan: "latest"
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
            conan: "latest"
          - name: "ubuntu-py39"
            python: "3.9"
            use_coverage: true
            conan: "latest"
            os: ubuntu-latest
          - name: "windows-py38"
            python: "3.8"
            os: windows-latest
            use_coverage: true
            conan: "latest"
          - name: "ubuntu-py38-conan1.17"
            python: "3.8"
            os: ubuntu-latest
            conan: "1.17"
            use_coverage: true

    env:
      DISPLAY: ":99.0"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v2
      - name: Set up a display for gui in Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install xterm for testing in Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install gnome-terminal
          sudo apt install dbus-x11
      - name: Set up Python  ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install pip and Python test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
      - name: Install specific conan version
        if: matrix.conan != 'latest'
        run: |
          pip install conan==${{ matrix.conan }}
      - name: Install own dependencies
        run: |
          pip install .
      - name: Unit and Integration tests with pytest on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pytest -v test/unit --junit-xml=./result_unit.xml --cov-report=term --cov=conan_app_launcher --cov-branch --cov-append || :
          pytest -v test/integration --junit-xml=./result_integration.xml --cov-report=term --cov=conan_app_launcher --cov-branch --cov-append || :
      - name: Unit and Integration tests with pytest on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pytest -v test/unit --junit-xml=./result_unit.xml --cov-report=term --cov=conan_app_launcher --cov-branch --cov-append ||  EXIT /B 0
          pytest -v test/integration --junit-xml=./result_integration.xml --cov-report=term --cov=conan_app_launcher --cov-branch --cov-append ||  EXIT /B 0
      - name: Evaluate test results
        run: |
          python test/evaluation.py
